package PayStatistics;

import java.awt.Toolkit;
import PayStatistics.EmployeeGUI;

/**
 *
 * @author Mitchell
 */
public class About extends javax.swing.JFrame {

    /**
     *
     */
    public About() {
        initComponents();
        // center form
        this.setLocationRelativeTo(null);
        // set default button to add
        this.getRootPane().setDefaultButton(exitAboutJButton);
        // add icon to the form
        this.setIconImage(Toolkit.getDefaultToolkit().
                getImage("src/PayStatistics/EmployeeLogo.jpg"));
        exitAboutJButton.requestFocus();
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aboutTitleJPanel = new javax.swing.JPanel();
        employeesJLabel = new javax.swing.JLabel();
        aboutInfoJPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        aboutBaseJPanel = new javax.swing.JPanel();
        warningJLabel = new javax.swing.JLabel();
        exitAboutJButton = new javax.swing.JButton();
        copyrightJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        aboutTitleJPanel.setPreferredSize(new java.awt.Dimension(292, 22));

        employeesJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        employeesJLabel.setText("Employees Pay Statistics");

        javax.swing.GroupLayout aboutTitleJPanelLayout = new javax.swing.GroupLayout(aboutTitleJPanel);
        aboutTitleJPanel.setLayout(aboutTitleJPanelLayout);
        aboutTitleJPanelLayout.setHorizontalGroup(
            aboutTitleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutTitleJPanelLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(employeesJLabel)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        aboutTitleJPanelLayout.setVerticalGroup(
            aboutTitleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutTitleJPanelLayout.createSequentialGroup()
                .addComponent(employeesJLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        aboutInfoJPanel.setPreferredSize(new java.awt.Dimension(292, 157));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(25);
        jTextArea1.setFont(new java.awt.Font("Lucida Console", 0, 10)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(7);
        jTextArea1.setText("Purpose: Allow users to easily analyze, store and print employee pay statistics.\n\nAuthors: Mitchell Nye, Alexander Jordan\nClass: CS-142-2700\nInstructor: Niko Culevski\nPublish date: 1/27/2016");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout aboutInfoJPanelLayout = new javax.swing.GroupLayout(aboutInfoJPanel);
        aboutInfoJPanel.setLayout(aboutInfoJPanelLayout);
        aboutInfoJPanelLayout.setHorizontalGroup(
            aboutInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutInfoJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addContainerGap())
        );
        aboutInfoJPanelLayout.setVerticalGroup(
            aboutInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutInfoJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        warningJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        warningJLabel.setText("Warning");

        exitAboutJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        exitAboutJButton.setMnemonic('c');
        exitAboutJButton.setText("Close");
        exitAboutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitAboutJButtonActionPerformed(evt);
            }
        });

        copyrightJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        copyrightJLabel.setText("Copyright");

        javax.swing.GroupLayout aboutBaseJPanelLayout = new javax.swing.GroupLayout(aboutBaseJPanel);
        aboutBaseJPanel.setLayout(aboutBaseJPanelLayout);
        aboutBaseJPanelLayout.setHorizontalGroup(
            aboutBaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutBaseJPanelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(warningJLabel)
                .addGap(40, 40, 40)
                .addComponent(exitAboutJButton)
                .addGap(40, 40, 40)
                .addComponent(copyrightJLabel)
                .addContainerGap())
        );
        aboutBaseJPanelLayout.setVerticalGroup(
            aboutBaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutBaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(exitAboutJButton)
                .addComponent(warningJLabel)
                .addComponent(copyrightJLabel))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(aboutTitleJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aboutBaseJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aboutInfoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(aboutTitleJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aboutInfoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(aboutBaseJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitAboutJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitAboutJButtonActionPerformed
        // end application
        this.dispose();
    }//GEN-LAST:event_exitAboutJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new About().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutBaseJPanel;
    private javax.swing.JPanel aboutInfoJPanel;
    private javax.swing.JPanel aboutTitleJPanel;
    private javax.swing.JLabel copyrightJLabel;
    private javax.swing.JLabel employeesJLabel;
    private javax.swing.JButton exitAboutJButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel warningJLabel;
    // End of variables declaration//GEN-END:variables
}
